name: Mirror images to RHISV Quay Org

on:
  workflow_call:
    inputs:
      sourceImageName:
        required: true
        type: string
      sourceImageTag:
        required: true
        type: string
      destImageName:
        required: true
        type: string
    secrets:
      sourceImageRegistry:
        required: true
      destImageRegistry:
        required: true
      destRegistryUser:
        required: true
      destRegistryPassword:
        required: true

jobs:
  mirror-images-to-rhisv:
    name: Mirror Images
    runs-on: ubuntu-latest
    steps:
    - name: Podman Login
      uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
      with:
        registry: ${DEST_IMAGE_REGISTRY}
        username: ${{ secrets.destRegistryUser }}
        password: ${{ secrets.destRegistryPassword }}

    - name: Copy Images from Source to Dest
      id: skopeo-copy-image
      run: |
        skopeo -v
        skopeo copy --all --preserve-digests "docker://${SOURCE_IMAGE_REGISTRY}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-amd64" "docker://${DEST_IMAGE_REGISTRY}/${DEST_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-amd64"
        skopeo copy --all --preserve-digests "docker://${SOURCE_IMAGE_REGISTRY}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-ppc64le" "docker://${DEST_IMAGE_REGISTRY}/${DEST_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-ppc64le"
        skopeo copy --all --preserve-digests "docker://${SOURCE_IMAGE_REGISTRY}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-arm64" "docker://${DEST_IMAGE_REGISTRY}/${DEST_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-arm64"
        skopeo copy --all --preserve-digests "docker://${SOURCE_IMAGE_REGISTRY}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-s390x" "docker://${DEST_IMAGE_REGISTRY}/${DEST_IMAGE_NAME}:${SOURCE_IMAGE_TAG}-linux-s390x"
        skopeo copy --all --preserve-digests "docker://${SOURCE_IMAGE_REGISTRY}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}" "docker://${DEST_IMAGE_REGISTRY}/${DEST_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
      env:
        SOURCE_IMAGE_REGISTRY: ${{ secrets.sourceImageRegistry }}
        SOURCE_IMAGE_NAME: ${{ inputs.sourceImageName }}
        SOURCE_IMAGE_TAG: ${{ inputs.sourceImageTag }}
        DEST_IMAGE_REGISTRY: ${{ secrets.destImageRegistry }}
        DEST_IMAGE_NAME: ${{ inputs.destImageName }}
