name: Go

on:
  pull_request:
    branches:
    - main
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install system deps
      run: 'sudo apt update && sudo apt install -y libgpgme-dev libbtrfs-dev libdevmapper-dev'

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Tidy
      run: make tidy

    - name: Vet
      run: make vet

    - name: Format
      run: make fmt

    - name: Run golangci linting checks
      run: make lint

    - name: Test
      run: make cover

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.out

  build-linux-binaries:
    name: Build Multi-arch-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux ]
        architecture:
          - amd64
          - arm64
          - ppc64le
          - s390x
    steps:
      - uses: actions/checkout@v4
      - name: Build linux binary for ${{ matrix.architecture }}
        run: make build-linux-${{ matrix.architecture }}

  build-mac-binaries:
    name: Build Multi-arch-mac
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Build Mac binary for ${{ matrix.architecture }}
        run: make build-mac-${{ matrix.architecture }}
